In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
df=pd.read_csv('train_storming_round.csv')
df['agent_join_month']=pd.to_datetime(df['agent_join_month'])
df['year_month']=pd.to_datetime(df['year_month'])
df['first_policy_sold_month']=pd.to_datetime(df['first_policy_sold_month'])
df

,row_id,agent_code,agent_age,agent_join_month,first_policy_sold_month,year_month,unique_proposals_last_7_days,unique_proposals_last_15_days,unique_proposals_last_21_days,unique_proposal,...,unique_quotations,unique_customers_last_7_days,unique_customers_last_15_days,unique_customers_last_21_days,unique_customers,new_policy_count,ANBP_value,net_income,number_of_policy_holders,number_of_cash_payment_policies
0,1,455ca878,45,2021-02-01,2023-09-01,2023-01-01,3,6,2,12,...,9,3,4,8,15,0,0,93313,30,162
1,2,c823ce77,48,2022-04-01,2024-02-01,2023-01-01,1,4,12,21,...,14,4,3,10,17,25,1071450,164804,0,175
2,3,62154055,53,2020-05-01,2023-09-01,2023-01-01,3,5,5,17,...,14,3,7,11,21,26,1601210,426690,84,78
3,4,c58bfa6e,44,2019-07-01,2022-03-01,2023-01-01,1,0,12,17,...,11,2,2,9,13,18,283230,47793,39,144
4,5,b1e5f770,20,2020-09-01,2023-02-01,2023-01-01,0,6,10,17,...,13,3,10,6,19,20,1957680,562239,19,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15303,15304,d3b44e44,43,2019-04-01,2023-10-01,2024-08-01,1,6,6,17,...,10,3,4,11,18,25,2473900,404980,18,100
15304,15305,0b1d7054,28,2022-09-01,2024-03-01,2024-08-01,1,5,3,13,...,14,4,3,11,18,15,922050,198187,18,120
15305,15306,51321fa2,45,2021-01-01,2024-04-01,2024-08-01,0,6,17,26,...,22,6,7,6,19,30,645330,133263,57,270
15306,15307,dd4a0d2d,25,2021-12-01,2023-12-01,2024-08-01,0,4,6,14,...,13,6,3,6,15,0,0,32546,30,171
15307,15308,393f3bf6,53,2023-01-01,2024-02-01,2024-08-01,1,4,7,16,...,9,3,8,1,12,19,1726568,295565,36,0

In [16]:
df['training_experience']=(df['year_month']-df['agent_join_month']).dt.days
df['practical_experience']=(df['year_month']-df['first_policy_sold_month']).dt.days
df['agent_nill_next_month'] = (df.groupby('agent_code')['new_policy_count'].shift(-1) == 0).astype(int)

In [17]:
df=df[~(df['year_month']=='2024-08-01	')]
train=df[~(df['year_month']=='2024-07-01	')]
test=df[(df['year_month']=='2024-07-01	')]

In [18]:
df

,row_id,agent_code,agent_age,agent_join_month,first_policy_sold_month,year_month,unique_proposals_last_7_days,unique_proposals_last_15_days,unique_proposals_last_21_days,unique_proposal,...,unique_customers_last_21_days,unique_customers,new_policy_count,ANBP_value,net_income,number_of_policy_holders,number_of_cash_payment_policies,training_experience,practical_experience,agent_nill_next_month
0,1,455ca878,45,2021-02-01,2023-09-01,2023-01-01,3,6,2,12,...,8,15,0,0,93313,30,162,699,-243,0
1,2,c823ce77,48,2022-04-01,2024-02-01,2023-01-01,1,4,12,21,...,10,17,25,1071450,164804,0,175,275,-396,0
2,3,62154055,53,2020-05-01,2023-09-01,2023-01-01,3,5,5,17,...,11,21,26,1601210,426690,84,78,975,-243,0
3,4,c58bfa6e,44,2019-07-01,2022-03-01,2023-01-01,1,0,12,17,...,9,13,18,283230,47793,39,144,1280,306,0
4,5,b1e5f770,20,2020-09-01,2023-02-01,2023-01-01,0,6,10,17,...,6,19,20,1957680,562239,19,40,852,-31,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14398,14399,08a278cd,42,2023-08-01,2024-01-01,2024-07-01,0,1,15,21,...,9,19,27,2644407,612572,19,135,335,182,0
14399,14400,272f6f80,25,2024-06-01,2024-04-01,2024-07-01,3,5,20,29,...,11,17,31,984932,128415,34,62,30,91,0
14400,14401,817339ac,53,2020-02-01,2023-12-01,2024-07-01,1,1,17,24,...,0,6,26,1515410,244054,24,78,1612,213,0
14401,14402,026b60ee,57,2019-08-01,2022-03-01,2024-07-01,1,0,16,19,...,9,15,23,2132514,229389,30,0,1796,853,0
14402,14403,1630a967,45,2020-11-01,2022-01-01,2024-07-01,2,3,0,8,...,8,18,14,447062,91114,18,42,1338,912,0

In [19]:
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler
import joblib
def scale_dataset(df,oversample):
    df=df.drop(['unique_proposals_last_7_days',
'unique_proposals_last_15_days',
'unique_proposals_last_21_days',
'unique_quotations_last_7_days',
'unique_quotations_last_15_days',
'unique_quotations_last_21_days',
'unique_customers_last_7_days',
'unique_customers_last_15_days',
'unique_customers_last_21_days'],axis=1)
    x=df[df.columns[6:-1]].values
    y=df['agent_nill_next_month'].values
    if oversample:
        ros=RandomOverSampler(random_state=42)
        x,y=ros.fit_resample(x,y)
        scaler=StandardScaler()
        x=scaler.fit_transform(x)
        joblib.dump(scaler,'standard_scaler.joblib')
    else:
        scaler=joblib.load('standard_scaler.joblib')
        x=scaler.transform(x)
    return x,y

In [20]:
train_x,train_y=scale_dataset(train,True)
test_x,test_y=scale_dataset(test,False)

In [21]:
from xgboost import XGBClassifier
model=XGBClassifier(n_estimators=200,random_state=42)
model.fit(train_x,train_y)
predict_y=model.predict(test_x)

In [22]:
from sklearn.metrics import classification_report
print(classification_report(test_y,predict_y))

              precision    recall  f1-score   support

           0       0.90      0.96      0.93       802
           1       0.10      0.04      0.06        90

    accuracy                           0.86       892
   macro avg       0.50      0.50      0.49       892
weighted avg       0.82      0.86      0.84       892

In [23]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,predict_y)

array([[767,  35],
       [ 86,   4]], dtype=int64)

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y,predict_y)

0.8643497757847534